language: python
python:
  - "2.6"
  - "2.7"
script: nosetests
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-qt4
install:
  - pip install mutagen
branches:
  only:
    - master
