# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../../ui/main.ui'
#
# Created: Tue Nov  2 01:54:08 2010
#      by: PyQt4 UI code generator 4.8
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName(_fromUtf8("main"))
        main.resize(723, 591)
        self.verticalLayout = QtGui.QVBoxLayout(main)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widget = QtGui.QWidget(main)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter = QtGui.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.artists = QtGui.QTreeWidget(self.splitter)
        self.artists.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.artists.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.artists.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.artists.setIndentation(0)
        self.artists.setItemsExpandable(False)
        self.artists.setColumnCount(3)
        self.artists.setObjectName(_fromUtf8("artists"))
        self.artists.headerItem().setText(0, _fromUtf8("1"))
        self.artists.headerItem().setText(1, _fromUtf8("2"))
        self.artists.headerItem().setText(2, _fromUtf8("3"))
        self.albums = QtGui.QTreeWidget(self.splitter)
        self.albums.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.albums.setAlternatingRowColors(True)
        self.albums.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.albums.setIndentation(0)
        self.albums.setItemsExpandable(False)
        self.albums.setColumnCount(4)
        self.albums.setObjectName(_fromUtf8("albums"))
        self.albums.headerItem().setText(0, _fromUtf8("1"))
        self.albums.headerItem().setText(1, _fromUtf8("2"))
        self.albums.headerItem().setText(2, _fromUtf8("3"))
        self.albums.headerItem().setText(3, _fromUtf8("4"))
        self.tracks = QtGui.QTreeWidget(self.splitter)
        self.tracks.setIndentation(0)
        self.tracks.setItemsExpandable(False)
        self.tracks.setColumnCount(2)
        self.tracks.setObjectName(_fromUtf8("tracks"))
        self.tracks.headerItem().setText(0, _fromUtf8("1"))
        self.tracks.headerItem().setText(1, _fromUtf8("2"))
        self.horizontalLayout.addWidget(self.splitter)
        self.verticalLayout.addWidget(self.widget)
        self.widget_3 = QtGui.QWidget(main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.artistsStats = QtGui.QGroupBox(self.widget_3)
        self.artistsStats.setObjectName(_fromUtf8("artistsStats"))
        self.formLayout = QtGui.QFormLayout(self.artistsStats)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.artistsGreen = QtGui.QLabel(self.artistsStats)
        self.artistsGreen.setObjectName(_fromUtf8("artistsGreen"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.artistsGreen)
        self.frame_2 = QtGui.QFrame(self.artistsStats)
        self.frame_2.setMinimumSize(QtCore.QSize(30, 30))
        self.frame_2.setStyleSheet(_fromUtf8("background-color: yellow;"))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.frame_2)
        self.artistsYellow = QtGui.QLabel(self.artistsStats)
        self.artistsYellow.setObjectName(_fromUtf8("artistsYellow"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.artistsYellow)
        self.frame_3 = QtGui.QFrame(self.artistsStats)
        self.frame_3.setMinimumSize(QtCore.QSize(30, 30))
        self.frame_3.setStyleSheet(_fromUtf8("background-color: red;"))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.frame_3)
        self.artistsRed = QtGui.QLabel(self.artistsStats)
        self.artistsRed.setObjectName(_fromUtf8("artistsRed"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.artistsRed)
        self.frame = QtGui.QFrame(self.artistsStats)
        self.frame.setMinimumSize(QtCore.QSize(30, 30))
        self.frame.setStyleSheet(_fromUtf8("background-color: green;"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.frame)
        self.horizontalLayout_2.addWidget(self.artistsStats)
        self.albumsStats = QtGui.QGroupBox(self.widget_3)
        self.albumsStats.setObjectName(_fromUtf8("albumsStats"))
        self.formLayout_2 = QtGui.QFormLayout(self.albumsStats)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.frame_6 = QtGui.QFrame(self.albumsStats)
        self.frame_6.setMinimumSize(QtCore.QSize(30, 30))
        self.frame_6.setStyleSheet(_fromUtf8("background-color: green;"))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.frame_6)
        self.albumsGreen = QtGui.QLabel(self.albumsStats)
        self.albumsGreen.setObjectName(_fromUtf8("albumsGreen"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.albumsGreen)
        self.frame_5 = QtGui.QFrame(self.albumsStats)
        self.frame_5.setMinimumSize(QtCore.QSize(30, 30))
        self.frame_5.setStyleSheet(_fromUtf8("background-color: yellow;"))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.frame_5)
        self.albumsYellow = QtGui.QLabel(self.albumsStats)
        self.albumsYellow.setObjectName(_fromUtf8("albumsYellow"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.albumsYellow)
        self.frame_4 = QtGui.QFrame(self.albumsStats)
        self.frame_4.setMinimumSize(QtCore.QSize(30, 30))
        self.frame_4.setStyleSheet(_fromUtf8("background-color: red;"))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.frame_4)
        self.albumsRed = QtGui.QLabel(self.albumsStats)
        self.albumsRed.setObjectName(_fromUtf8("albumsRed"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.albumsRed)
        self.horizontalLayout_2.addWidget(self.albumsStats)
        self.tracksStats = QtGui.QGroupBox(self.widget_3)
        self.tracksStats.setObjectName(_fromUtf8("tracksStats"))
        self.formLayout_4 = QtGui.QFormLayout(self.tracksStats)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.frame_7 = QtGui.QFrame(self.tracksStats)
        self.frame_7.setMinimumSize(QtCore.QSize(30, 30))
        self.frame_7.setStyleSheet(_fromUtf8("background-color: green;"))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.frame_7)
        self.tracksGreen = QtGui.QLabel(self.tracksStats)
        self.tracksGreen.setObjectName(_fromUtf8("tracksGreen"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.tracksGreen)
        self.frame_8 = QtGui.QFrame(self.tracksStats)
        self.frame_8.setMinimumSize(QtCore.QSize(30, 30))
        self.frame_8.setStyleSheet(_fromUtf8("background-color: yellow;"))
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.frame_8)
        self.tracksYellow = QtGui.QLabel(self.tracksStats)
        self.tracksYellow.setObjectName(_fromUtf8("tracksYellow"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.tracksYellow)
        self.frame_9 = QtGui.QFrame(self.tracksStats)
        self.frame_9.setMinimumSize(QtCore.QSize(30, 30))
        self.frame_9.setStyleSheet(_fromUtf8("background-color: red;"))
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.frame_9)
        self.tracksRed = QtGui.QLabel(self.tracksStats)
        self.tracksRed.setObjectName(_fromUtf8("tracksRed"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.tracksRed)
        self.horizontalLayout_2.addWidget(self.tracksStats)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.widget_2 = QtGui.QWidget(self.widget_3)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.formLayout_3 = QtGui.QFormLayout(self.widget_2)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.local = QtGui.QPushButton(self.widget_2)
        self.local.setMaximumSize(QtCore.QSize(61, 16777215))
        self.local.setObjectName(_fromUtf8("local"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.local)
        self.settings = QtGui.QPushButton(self.widget_2)
        self.settings.setMaximumSize(QtCore.QSize(61, 16777215))
        self.settings.setObjectName(_fromUtf8("settings"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.settings)
        self.remote = QtGui.QPushButton(self.widget_2)
        self.remote.setMaximumSize(QtCore.QSize(61, 16777215))
        self.remote.setObjectName(_fromUtf8("remote"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.remote)
        self.save = QtGui.QPushButton(self.widget_2)
        self.save.setMaximumSize(QtCore.QSize(61, 16777215))
        self.save.setObjectName(_fromUtf8("save"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.save)
        self.log = QtGui.QPushButton(self.widget_2)
        self.log.setMaximumSize(QtCore.QSize(61, 16777215))
        self.log.setObjectName(_fromUtf8("log"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.log)
        self.close = QtGui.QPushButton(self.widget_2)
        self.close.setMaximumSize(QtCore.QSize(61, 16777215))
        self.close.setObjectName(_fromUtf8("close"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.close)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.widget_3)

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        self.artists.setSortingEnabled(True)
        self.albums.setSortingEnabled(True)
        self.tracks.setSortingEnabled(True)
        self.artistsStats.setTitle(QtGui.QApplication.translate("main", "Artists", None, QtGui.QApplication.UnicodeUTF8))
        self.albumsStats.setTitle(QtGui.QApplication.translate("main", "Albums", None, QtGui.QApplication.UnicodeUTF8))
        self.tracksStats.setTitle(QtGui.QApplication.translate("main", "Tracks", None, QtGui.QApplication.UnicodeUTF8))
        self.local.setText(QtGui.QApplication.translate("main", "&Local", None, QtGui.QApplication.UnicodeUTF8))
        self.settings.setText(QtGui.QApplication.translate("main", "S&ettings", None, QtGui.QApplication.UnicodeUTF8))
        self.remote.setStatusTip(QtGui.QApplication.translate("main", "Refresh internet databases.", None, QtGui.QApplication.UnicodeUTF8))
        self.remote.setText(QtGui.QApplication.translate("main", "&Remote", None, QtGui.QApplication.UnicodeUTF8))
        self.save.setStatusTip(QtGui.QApplication.translate("main", "Save current database to disk. (Do it if you don\'t like your changes to be lost!)", None, QtGui.QApplication.UnicodeUTF8))
        self.save.setText(QtGui.QApplication.translate("main", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.log.setStatusTip(QtGui.QApplication.translate("main", "Access internet refreshing logs.", None, QtGui.QApplication.UnicodeUTF8))
        self.log.setText(QtGui.QApplication.translate("main", "L&ogs", None, QtGui.QApplication.UnicodeUTF8))
        self.close.setStatusTip(QtGui.QApplication.translate("main", "Close the application.", None, QtGui.QApplication.UnicodeUTF8))
        self.close.setText(QtGui.QApplication.translate("main", "&Close", None, QtGui.QApplication.UnicodeUTF8))

