# -*- coding: utf-8 -*-

from PyQt4 import QtGui
from PyQt4.QtCore import QSettings, Qt, pyqtSignal

class Settings(QtGui.QDialog):
    dirChanged = pyqtSignal(str)
    __settings=QSettings(u'fetcher',u'Fetcher')
    def __init__(self,parent=None):
        QtGui.QDialog.__init__(self,parent)
        tabs = QtGui.QTabWidget()
        info = QtGui.QLabel()
        self.dbList = QtGui.QListWidget()
        item = QtGui.QListWidgetItem(u'metal-archives.com')
        item.setFlags(item.flags() | Qt.ItemIsUserCheckable)
        item.setCheckState(self.__settings.value(u'metalArchives', 0).toInt()[0])
        self.dbList.addItem(item)
        item = QtGui.QListWidgetItem(u'discogs.com')
        item.setFlags(item.flags() | Qt.ItemIsUserCheckable)
        item.setCheckState(self.__settings.value(u'discogs', 0).toInt()[0])
        self.dbList.addItem(item)
        tabs.addTab(self.dbList, self.tr(u'&Databases'))
        fsDirLabel = QtGui.QLabel(u'Directory')
        directory = self.__settings.value(u'directory', u'').toString()
        self.fsDir = QtGui.QLineEdit(directory)
        fsDirButton = QtGui.QPushButton(self.tr(u'&Browse'))
        fsDirButton.clicked.connect(self.selectDir)
        fsDirLayout = QtGui.QHBoxLayout()
        fsDirLayout.addWidget(fsDirLabel)
        fsDirLayout.addWidget(self.fsDir)
        fsDirLayout.addWidget(fsDirButton)
        fsLabel = QtGui.QLabel(u'Ignores:')
        self.fsIgnores = QtGui.QListWidget()
        ignores = self.__settings.value(u'ignores', []).toPyObject()
        for i in ignores:
            item = QtGui.QListWidgetItem(i[0])
            item.setFlags(item.flags() | Qt.ItemIsUserCheckable)
            item.setCheckState(i[1])
            self.fsIgnores.addItem(item)
        self.fsName = QtGui.QLineEdit()
        fsAdd = QtGui.QPushButton(self.tr(u'&Add'))
        fsAdd.clicked.connect(self.add)
        fsRemove = QtGui.QPushButton(self.tr(u'&Remove'))
        fsButtonsLayout = QtGui.QHBoxLayout()
        fsButtonsLayout.addWidget(self.fsName)
        fsButtonsLayout.addWidget(fsAdd)
        fsButtonsLayout.addWidget(fsRemove)
        fsLayout = QtGui.QVBoxLayout()
        fsLayout.addLayout(fsDirLayout)
        fsLayout.addWidget(fsLabel)
        fsLayout.addWidget(self.fsIgnores)
        fsLayout.addLayout(fsButtonsLayout)
        fsWidget = QtGui.QWidget()
        fsWidget.setLayout(fsLayout)
        tabs.addTab(fsWidget, self.tr(u'&Local'))
        self.logsList = QtGui.QListWidget()
        item = QtGui.QListWidgetItem(u'errors')
        item.setFlags(item.flags() | Qt.ItemIsUserCheckable)
        item.setCheckState(self.__settings.value(u'logs/errors', 2).toInt()[0])
        self.logsList.addItem(item)
        item = QtGui.QListWidgetItem(u'info')
        item.setFlags(item.flags() | Qt.ItemIsUserCheckable)
        item.setCheckState(self.__settings.value(u'logs/info', 0).toInt()[0])
        self.logsList.addItem(item)
        tabs.addTab(self.logsList, self.tr(u'L&ogs'))
        ok = QtGui.QPushButton(self.tr(u'&OK'))
        ok.clicked.connect(self.save)
        cancel = QtGui.QPushButton(self.tr(u'&Cancel'))
        cancel.clicked.connect(self.close)
        buttonsLayout = QtGui.QHBoxLayout()
        buttonsLayout.addStretch()
        buttonsLayout.addWidget(ok)
        buttonsLayout.addWidget(cancel)
        layout = QtGui.QVBoxLayout()
        layout.addWidget(tabs)
        layout.addWidget(info)
        layout.addLayout(buttonsLayout)
        self.setLayout(layout)
    def add(self):
        if self.fsName.text() != u'':
            item = QtGui.QListWidgetItem(self.fsName.text())
            item.setFlags(item.flags() | Qt.ItemIsUserCheckable)
            item.setCheckState(2)
            self.fsIgnores.addItem(item)
        self.fsName.clear()
    def selectDir(self):
        dialog = QtGui.QFileDialog()
        self.fsDir.setText(dialog.getExistingDirectory())
    def save(self):
        directory = self.fsDir.text()
        if directory == u'':
            dialog = QtGui.QMessageBox()
            dialog.setText(u'Directory field cannot be empty!')
        else:
            self.__settings.setValue(u'directory', self.fsDir.text())
            self.__settings.setValue(u'metalArchives', self.dbList.item(0).checkState())
            self.__settings.setValue(u'discogs', self.dbList.item(1).checkState())
            ignores = [(str(v.text()), v.checkState()) for v
                    in self.fsIgnores.findItems(u'*', Qt.MatchWildcard)]
            self.__settings.setValue(u'ignores', ignores)
            self.__settings.setValue(u'logs/errors', self.logsList.item(0).checkState())
            self.__settings.setValue(u'logs/info', self.logsList.item(1).checkState())
            self.close()
